import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../../utils/trpc";
import { useState } from "react";


const Dashboard: NextPage = () => {
    const createGame = trpc.game.createGame.useMutation();

    const games = trpc.game.getAll.useQuery();

    const [questions, setQuestions] = useState([
        {
            question: "Selam naber",
            answers: [
                {
                    answer: "iyiyim",
                    isCorrect: false,
                },
                {
                    answer: "Kötüyum",
                    isCorrect: true,
                },
            ],
        },
    ]);

    const addQuestion = () => {
        setQuestions([
            ...questions,
            {
                question: "",
                answers: [
                    {
                        answer: "",
                        isCorrect: false,
                    },
                    {
                        answer: "",
                        isCorrect: false,
                    },
                ],
            },
        ]);
    };

    const [gameName, setGameName] = useState("Hello this is a game");

    const createGameHandler = async () => {
        await createGame.mutateAsync({
            name: gameName,
            questions: [
                {
                    question: "test",
                    answers: [
                        {
                            answer: "test",
                            isCorrect: true,
                        },
                        {
                            answer: "test",
                            isCorrect: false,
                        }
                    ]
                },
            ],
        });
        games.refetch();
    };

    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="w-full min-h-screen">
                <div className="bg-purple-800 h-20 flex items-center justify-center">
                    <h1 className="justify-center align-middle text-yellow-300 font-bold font-mono text-xl">Tell Me Your Friend</h1>
                </div>
                <div className="p-4">
                    <h1 className="font-mono font-medium text-gray-400">Create Your Game</h1>
                    <input className="font-bold text-xl w-10/12 decoration-white over" placeholder={gameName} />
                </div>
                <div className="p-4">
                    <div className="">
                        <button className="bg-yellow-300 p-3 rounded-md ">Add Question</button>
                    </div>
                    <div>
                    </div>
                </div>
            </main>
        </>
    );
};

export default Dashboard;
